/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GDriveSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  clientId: "",
  clientSecret: "",
  refreshToken: "",
  accessToken: "",
  accessTokenExpiry: 0,
  folderId: "",
  folderName: "",
  autoSyncInterval: 5,
  lastSyncTime: 0,
  lastSyncStartedAt: 0,
  conflictStrategy: "newer",
  syncOnStartup: true,
  excludePatterns: ".obsidian,.trash",
  loginHint: "",
  syncInProgress: false
};
var SYNC_RECORD_PATH = ".obsidian/gdrive-sync-record.json";
var DRIVE_API = "https://www.googleapis.com/drive/v3";
var DRIVE_UPLOAD = "https://www.googleapis.com/upload/drive/v3";
var TOKEN_URL = "https://oauth2.googleapis.com/token";
var DEVICE_CODE_URL = "https://oauth2.googleapis.com/device/code";
var SCOPES = "https://www.googleapis.com/auth/drive.file";
var GDriveSyncPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.syncRecord = {};
    this.syncInterval = null;
    this.isSyncing = false;
    this.folderCache = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    await this.loadSyncRecord();
    if (this.settings.syncInProgress) {
      this.settings.syncInProgress = false;
      await this.persistSettingsData();
      new import_obsidian.Notice("Previous GDrive sync did not finish cleanly. The next sync will rebuild state.");
    }
    this.statusBarItem = this.addStatusBarItem();
    this.updateStatusBar("idle");
    this.addRibbonIcon("refresh-cw", "Sync with Google Drive", async () => {
      await this.runSync();
    });
    try {
      this.statusBarItem.setAttribute("title", "Click to sync with Google Drive");
      this.statusBarItem.style.cursor = "pointer";
      this.statusBarItem.onclick = async () => {
        await this.runSync();
      };
    } catch (e) {
      // noop: defensive in case statusBarItem is not an HTMLElement in some hosts
    }
    this.addCommand({
      id: "gdrive-sync-now",
      name: "Sync now",
      callback: () => this.runSync()
    });
    this.addCommand({
      id: "gdrive-sync-status",
      name: "Show sync status",
      callback: () => this.showSyncStatus()
    });
    this.addCommand({
      id: "gdrive-force-upload",
      name: "Force upload all files to Google Drive",
      callback: () => this.forceUploadAll()
    });
    this.addCommand({
      id: "gdrive-force-download",
      name: "Force download all files from Google Drive",
      callback: () => this.forceDownloadAll()
    });
    this.addSettingTab(new GDriveSyncSettingTab(this.app, this));
    this.startAutoSync();
    if (this.settings.syncOnStartup && this.settings.refreshToken) {
      setTimeout(() => this.runSync(), 3e3);
    }
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian.TFile)
          this.markLocalChange(file.path);
      })
    );
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian.TFile)
          this.markLocalChange(file.path);
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian.TFile)
          this.markLocalDelete(file.path);
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian.TFile) {
          this.markLocalDelete(oldPath);
          this.markLocalChange(file.path);
        }
      })
    );
  }
  onunload() {
    if (this.syncInterval)
      window.clearInterval(this.syncInterval);
  }
  // ─── Settings / Record ──────────────────────────────────────────────────────
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.normalizeOAuthSettings();
  }
  normalizeOAuthValue(value) {
    return String(value || "").replace(/[\s\u200B-\u200D\uFEFF]+/g, "");
  }
  normalizeOAuthSettings() {
    this.settings.clientId = this.normalizeOAuthValue(this.settings.clientId);
    this.settings.clientSecret = this.normalizeOAuthValue(this.settings.clientSecret);
    this.settings.refreshToken = String(this.settings.refreshToken || "").trim();
    this.settings.accessToken = String(this.settings.accessToken || "").trim();
  }
  getMaskedClientId() {
    const clientId = this.normalizeOAuthValue(this.settings.clientId);
    if (!clientId)
      return "Not set";
    if (clientId.length <= 16)
      return clientId;
    return `${clientId.slice(0, 10)}...${clientId.slice(-12)}`;
  }
  async persistSettingsData() {
    this.normalizeOAuthSettings();
    await this.saveData(this.settings);
  }
  async saveSettings() {
    await this.persistSettingsData();
    this.startAutoSync();
  }
  async loadSyncRecord() {
    try {
      const raw = await this.app.vault.adapter.read(SYNC_RECORD_PATH);
      const parsed = JSON.parse(raw);
      this.syncRecord = {};
      for (const [path, entry] of Object.entries(parsed || {})) {
        this.syncRecord[path] = this.normalizeSyncRecordEntry(path, entry);
      }
    } catch (e) {
      this.syncRecord = {};
    }
  }
  async saveSyncRecord() {
    try {
      await this.app.vault.adapter.write(
        SYNC_RECORD_PATH,
        JSON.stringify(this.syncRecord, null, 2)
      );
    } catch (e) {
    }
  }
  // ─── Status Bar ─────────────────────────────────────────────────────────────
  updateStatusBar(state, detail = "") {
    const icons = {
      idle: "\u2601",
      syncing: "\u21BB",
      error: "\u26A0"
    };
    const lastSync = this.settings.lastSyncTime ? new Date(this.settings.lastSyncTime).toLocaleTimeString() : "never";
    this.statusBarItem.setText(
      `${icons[state]} GDrive ${state === "idle" ? `(${lastSync})` : state === "error" ? `Error: ${detail}` : "syncing\u2026"}`
    );
  }
  // ─── Auto-sync ──────────────────────────────────────────────────────────────
  startAutoSync() {
    if (this.syncInterval)
      window.clearInterval(this.syncInterval);
    if (this.settings.autoSyncInterval > 0) {
      this.syncInterval = window.setInterval(
        () => this.runSync(),
        this.settings.autoSyncInterval * 60 * 1e3
      );
    }
  }
  // ─── OAuth ──────────────────────────────────────────────────────────────────
  async postForm(url, params) {
    const body = new URLSearchParams();
    for (const [key, value] of Object.entries(params)) {
      if (value !== void 0 && value !== null && value !== "") {
        body.append(key, String(value));
      }
    }
    try {
      const resp = await (0, import_obsidian.requestUrl)({
        url,
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: body.toString()
      });
      return resp.json;
    } catch (error) {
      const parsed = this.tryParseOAuthError(error);
      if (parsed)
        return parsed;
      throw error;
    }
  }
  getHttpStatus(error) {
    const directStatus = error == null ? void 0 : error.status;
    if (typeof directStatus === "number")
      return directStatus;
    const message = (error == null ? void 0 : error.message) || "";
    const match = message.match(/status\s+(\d{3})/i);
    if (match)
      return Number(match[1]);
    return 0;
  }
  async postTokenForm(params, allowSecretFallback = false) {
    const secret = (this.settings.clientSecret || "").trim();
    const withSecret = secret ? Object.assign({}, params, { client_secret: secret }) : Object.assign({}, params);
    try {
      const data = await this.postForm(TOKEN_URL, withSecret);
      if (!allowSecretFallback || !secret)
        return data;
      if ((data == null ? void 0 : data.error) === "invalid_client" || (data == null ? void 0 : data.error) === "unauthorized_client") {
        return await this.postForm(TOKEN_URL, params);
      }
      return data;
    } catch (error) {
      if (!allowSecretFallback || !secret)
        throw error;
      if (this.getHttpStatus(error) === 401) {
        try {
          return await this.postForm(TOKEN_URL, params);
        } catch (fallbackError) {
          const fallbackStatus = this.getHttpStatus(fallbackError);
          if (fallbackStatus === 401) {
            return {
              error: "invalid_client",
              error_description: "Google rejected this OAuth client for the mobile token request."
            };
          }
          throw fallbackError;
        }
      }
      throw error;
    }
  }
  tryParseOAuthError(error) {
    const status = this.getHttpStatus(error);
    if (status === 428) {
      return {
        error: "authorization_pending",
        error_description: "Precondition Required"
      };
    }
    if (status === 429) {
      return {
        error: "slow_down",
        error_description: "Too Many Requests"
      };
    }
    if (status === 403 && ((error == null ? void 0 : error.message) || "").includes("status 403")) {
      return {
        error: "access_denied",
        error_description: "Forbidden"
      };
    }
    if (status === 401) {
      return {
        error: "invalid_client",
        error_description: "Google rejected this OAuth client."
      };
    }
    const candidates = [
      error == null ? void 0 : error.text,
      error == null ? void 0 : error.responseText,
      error == null ? void 0 : error.responseJson,
      error == null ? void 0 : error.response
    ];
    for (const candidate of candidates) {
      if (!candidate)
        continue;
      if (typeof candidate === "object")
        return candidate;
      if (typeof candidate === "string") {
        try {
          return JSON.parse(candidate);
        } catch (e) {
        }
      }
    }
    return null;
  }
  formatOAuthError(data, flow = "device") {
    if ((data == null ? void 0 : data.error) === "invalid_client") {
      const clientType = flow === "device" ? "TVs and Limited Input devices" : "Desktop app";
      return `Google could not find this OAuth client. Create OAuth credentials of type "${clientType}" in Google Cloud, then paste that Client ID and Secret here.`;
    }
    if ((data == null ? void 0 : data.error) === "access_denied")
      return "Access was denied in Google. Please try again.";
    if ((data == null ? void 0 : data.error) === "expired_token")
      return "This sign-in session expired. Please start again.";
    return (data == null ? void 0 : data.error_description) || (data == null ? void 0 : data.error) || "Unknown Google authentication error.";
  }
  async requestDeviceCode() {
    const data = await this.postForm(DEVICE_CODE_URL, {
      client_id: this.settings.clientId,
      scope: SCOPES
    });
    if (data.error)
      throw new Error(this.formatOAuthError(data));
    return {
      deviceCode: data.device_code,
      userCode: data.user_code,
      verificationUrl: data.verification_url,
      expiresAt: Date.now() + data.expires_in * 1e3,
      intervalMs: Math.max((data.interval || 5) * 1e3, 5e3)
    };
  }
  async sleep(ms) {
    await new Promise((resolve) => window.setTimeout(resolve, ms));
  }
  async pollForDeviceTokens(deviceAuth, onStatus, shouldCancel = () => false) {
    let intervalMs = deviceAuth.intervalMs;
    while (Date.now() < deviceAuth.expiresAt) {
      if (shouldCancel())
        throw new Error("cancelled");
      if (onStatus)
        onStatus("Waiting for approval in Google...");
      const data = await this.postTokenForm({
        client_id: this.settings.clientId,
        device_code: deviceAuth.deviceCode,
        grant_type: "urn:ietf:params:oauth:grant-type:device_code"
      }, true);
      if (data.access_token) {
        this.settings.accessToken = data.access_token;
        this.settings.refreshToken = data.refresh_token;
        this.settings.accessTokenExpiry = Date.now() + data.expires_in * 1e3;
        await this.saveSettings();
        return;
      }
      if (data.error === "authorization_pending") {
        await this.sleep(intervalMs);
        continue;
      }
      if (data.error === "slow_down") {
        intervalMs += 5e3;
        await this.sleep(intervalMs);
        continue;
      }
      throw new Error(this.formatOAuthError(data));
    }
    throw new Error("This sign-in code expired. Please start the sign-in process again.");
  }
  async refreshAccessToken() {
    if (!this.settings.refreshToken)
      throw new Error("Not authenticated. Please sign in from settings.");
    const data = await this.postTokenForm({
      refresh_token: this.settings.refreshToken,
      client_id: this.settings.clientId,
      grant_type: "refresh_token"
    }, true);
    if (data.error)
      throw new Error(this.formatOAuthError(data));
    this.settings.accessToken = data.access_token;
    this.settings.accessTokenExpiry = Date.now() + data.expires_in * 1e3;
    await this.saveSettings();
  }
  async getAccessToken() {
    if (!this.settings.accessToken || Date.now() >= this.settings.accessTokenExpiry - 6e4) {
      await this.refreshAccessToken();
    }
    return this.settings.accessToken;
  }
  normalizeSyncRecordEntry(filePath, entry = {}) {
    return Object.assign({
      path: filePath,
      driveId: "",
      driveMtime: 0,
      localMtime: 0,
      md5: "",
      localHash: "",
      deleted: false,
      deletedAt: 0,
      dirty: false
    }, entry || {}, { path: filePath });
  }
  buildSyncRecordEntry(filePath, entry = {}) {
    return this.normalizeSyncRecordEntry(filePath, entry);
  }
  escapeDriveQueryValue(value) {
    return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
  }
  getParentPath(filePath) {
    const lastSlash = filePath.lastIndexOf("/");
    return lastSlash === -1 ? "" : filePath.slice(0, lastSlash);
  }
  withCharset(mimeType) {
    if (mimeType.startsWith("text/") || mimeType.includes("json") || mimeType.includes("javascript") || mimeType.includes("xml")) {
      return mimeType.includes("charset=") ? mimeType : `${mimeType}; charset=UTF-8`;
    }
    return mimeType;
  }
  getMimeTypeForPath(filePath) {
    const extension = (filePath.split(".").pop() || "").toLowerCase();
    const mimeMap = {
      md: "text/markdown",
      txt: "text/plain",
      canvas: "application/json",
      json: "application/json",
      css: "text/css",
      js: "application/javascript",
      ts: "application/typescript",
      html: "text/html",
      xml: "application/xml",
      csv: "text/csv",
      svg: "image/svg+xml",
      png: "image/png",
      jpg: "image/jpeg",
      jpeg: "image/jpeg",
      gif: "image/gif",
      webp: "image/webp",
      pdf: "application/pdf",
      mp3: "audio/mpeg",
      m4a: "audio/mp4",
      wav: "audio/wav",
      mp4: "video/mp4",
      mov: "video/quicktime"
    };
    return this.withCharset(mimeMap[extension] || "application/octet-stream");
  }
  isTextMimeType(mimeType) {
    return mimeType.startsWith("text/") || mimeType.includes("json") || mimeType.includes("javascript") || mimeType.includes("xml") || mimeType === "image/svg+xml";
  }
  toUint8Array(data) {
    return data instanceof Uint8Array ? data : new Uint8Array(data);
  }
  async hashArrayBuffer(data) {
    const digest = await crypto.subtle.digest("SHA-256", data);
    return Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, "0")).join("");
  }
  async requestWithRetry(options, attempt = 0) {
    try {
      return await (0, import_obsidian.requestUrl)(options);
    } catch (error) {
      if (!this.shouldRetryRequest(error, attempt))
        throw error;
      const delay = Math.min(3e4, 1e3 * 2 ** attempt);
      await this.sleep(delay);
      return this.requestWithRetry(options, attempt + 1);
    }
  }
  shouldRetryRequest(error, attempt) {
    if (attempt >= 4)
      return false;
    const status = error == null ? void 0 : error.status;
    if (status === 408 || status === 409 || status === 425 || status === 429 || status >= 500)
      return true;
    const parsed = this.tryParseOAuthError(error);
    const text = JSON.stringify(parsed || {});
    return /rateLimitExceeded|userRateLimitExceeded|backendError|internalError/i.test(text);
  }
  // ─── Drive API helpers ──────────────────────────────────────────────────────
  async driveRequest(url, options = {}) {
    const token = await this.getAccessToken();
    const resp = await this.requestWithRetry({
      url,
      ...options,
      headers: {
        Authorization: `Bearer ${token}`,
        ...options.headers || {}
      }
    });
    return resp.json;
  }
  async ensureVaultFolder() {
    if (this.settings.folderId)
      return this.settings.folderId;
    const vaultName = this.app.vault.getName() || "ObsidianVault";
    const query = `name='${this.escapeDriveQueryValue(vaultName)}' and mimeType='application/vnd.google-apps.folder' and trashed=false`;
    const search = await this.driveRequest(
      `${DRIVE_API}/files?q=${encodeURIComponent(query)}&fields=files(id,name)&pageSize=10`
    );
    if (search.files && search.files.length > 0) {
      this.settings.folderId = search.files[0].id;
      this.settings.folderName = vaultName;
      await this.persistSettingsData();
      return this.settings.folderId;
    }
    const token = await this.getAccessToken();
    const created = await this.requestWithRetry({
      url: `${DRIVE_API}/files`,
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        name: vaultName,
        mimeType: "application/vnd.google-apps.folder",
        appProperties: {
          managedBy: this.manifest.id,
          vaultPath: ""
        }
      })
    });
    const data = created.json;
    this.settings.folderId = data.id;
    this.settings.folderName = vaultName;
    await this.persistSettingsData();
    return this.settings.folderId;
  }
  async createDriveFolder(name, parentId, folderPath) {
    const token = await this.getAccessToken();
    const created = await this.requestWithRetry({
      url: `${DRIVE_API}/files`,
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        name,
        parents: [parentId],
        mimeType: "application/vnd.google-apps.folder",
        appProperties: {
          managedBy: this.manifest.id,
          vaultPath: folderPath
        }
      })
    });
    return created.json;
  }
  async createDeletionMarker(vaultPath) {
    try {
      const token = await this.getAccessToken();
      const parentId = await this.ensureDriveFolderPath(this.getParentPath(vaultPath));
      const metadata = {
        name: vaultPath.split("/").pop(),
        parents: [parentId],
        mimeType: "application/octet-stream",
        appProperties: {
          managedBy: this.manifest.id,
          vaultPath,
          deleted: "1"
        }
      };
      const created = await this.requestWithRetry({
        url: `${DRIVE_API}/files`,
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify(metadata)
      });
      return created.json;
    } catch (e) {
      console.error("GDrive Sync: failed to create deletion marker", e);
      return null;
    }
  }
  async listDriveChildren(parentId) {
    const files = [];
    let pageToken = "";
    do {
      const query = `'${parentId}' in parents and trashed=false`;
      const url = `${DRIVE_API}/files?q=${encodeURIComponent(query)}&fields=nextPageToken,files(id,name,mimeType,modifiedTime,md5Checksum,parents,appProperties,size)&pageSize=1000` + (pageToken ? `&pageToken=${pageToken}` : "");
      const data = await this.driveRequest(url);
      if (data.files)
        files.push(...data.files);
      pageToken = data.nextPageToken || "";
    } while (pageToken);
    return files;
  }
  async ensureDriveFolderPath(folderPath) {
    const rootId = await this.ensureVaultFolder();
    this.folderCache.set("", rootId);
    if (!folderPath)
      return rootId;
    if (this.folderCache.has(folderPath))
      return this.folderCache.get(folderPath);
    const segments = folderPath.split("/").filter(Boolean);
    let parentId = rootId;
    let currentPath = "";
    for (const segment of segments) {
      currentPath = currentPath ? `${currentPath}/${segment}` : segment;
      if (this.folderCache.has(currentPath)) {
        parentId = this.folderCache.get(currentPath);
        continue;
      }
      const query = [
        `'${parentId}' in parents`,
        `name='${this.escapeDriveQueryValue(segment)}'`,
        `mimeType='application/vnd.google-apps.folder'`,
        "trashed=false"
      ].join(" and ");
      const search = await this.driveRequest(
        `${DRIVE_API}/files?q=${encodeURIComponent(query)}&fields=files(id,name,appProperties)&pageSize=20`
      );
      const matches = search.files || [];
      const existing = matches.find((file) => {
        var _a;
        return ((_a = file.appProperties) == null ? void 0 : _a.vaultPath) === currentPath;
      }) || matches[0];
      const folder = existing || await this.createDriveFolder(segment, parentId, currentPath);
      this.folderCache.set(currentPath, folder.id);
      parentId = folder.id;
    }
    return parentId;
  }
  buildMultipartBody(metadata, fileData, mimeType) {
    const boundary = `gdrive_sync_${Date.now().toString(36)}`;
    const encoder = new TextEncoder();
    const prefix = encoder.encode(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: ${mimeType}\r\n\r\n`);
    const suffix = encoder.encode(`\r\n--${boundary}--`);
    const bytes = this.toUint8Array(fileData);
    const body = new Uint8Array(prefix.length + bytes.length + suffix.length);
    body.set(prefix, 0);
    body.set(bytes, prefix.length);
    body.set(suffix, prefix.length + bytes.length);
    return { boundary, body: body.buffer };
  }
  async readLocalFilePayload(localFile) {
    const mimeType = this.getMimeTypeForPath(localFile.path);
    const localMtime = localFile.stat && localFile.stat.mtime ? localFile.stat.mtime : Date.now();
    if (this.isTextMimeType(mimeType)) {
      const text = await this.app.vault.read(localFile);
      const data = new TextEncoder().encode(text).buffer;
      return {
        data,
        mimeType,
        localHash: await this.hashArrayBuffer(data),
        isText: true,
        localMtime
      };
    }
    const data = await this.app.vault.adapter.readBinary(localFile.path);
    return {
      data,
      mimeType,
      localHash: await this.hashArrayBuffer(data),
      isText: false,
      localMtime
    };
  }
  async ensureLocalFolder(folderPath) {
    if (!folderPath)
      return;
    const segments = folderPath.split("/").filter(Boolean);
    let currentPath = "";
    for (const segment of segments) {
      currentPath = currentPath ? `${currentPath}/${segment}` : segment;
      const existing = this.app.vault.getAbstractFileByPath(currentPath);
      if (!(existing instanceof import_obsidian.TFolder)) {
        await this.app.vault.createFolder(currentPath);
      }
    }
  }
  async writeLocalFile(remoteFile, data) {
    const localPath = remoteFile.vaultPath;
    const mimeType = remoteFile.mimeType || this.getMimeTypeForPath(localPath);
    await this.ensureLocalFolder(this.getParentPath(localPath));
    if (this.isTextMimeType(mimeType)) {
      const text = new TextDecoder("utf-8").decode(data);
      const existing = this.app.vault.getAbstractFileByPath(localPath);
      if (existing instanceof import_obsidian.TFile) {
        await this.app.vault.modify(existing, text);
      } else {
        await this.app.vault.create(localPath, text);
      }
    } else {
      await this.app.vault.adapter.writeBinary(localPath, data);
    }
    const current = this.app.vault.getAbstractFileByPath(localPath);
    const stat = current instanceof import_obsidian.TFile ? current.stat : await this.app.vault.adapter.stat(localPath);
    return {
      localMtime: (stat == null ? void 0 : stat.mtime) || Date.now(),
      localHash: await this.hashArrayBuffer(data)
    };
  }
  didLocalFileChange(record, payload, localMtime) {
    if (!record)
      return true;
    if (record.dirty)
      return true;
    if (record.localHash)
      return record.localHash !== payload.localHash;
    return localMtime > record.localMtime + 1e3;
  }
  didRemoteFileChange(record, remoteFile, remoteMtime) {
    if (!record)
      return true;
    if (record.driveId && remoteFile.id !== record.driveId)
      return true;
    if (record.md5 && remoteFile.md5Checksum)
      return record.md5 !== remoteFile.md5Checksum;
    // If the uploader recorded a content hash, use that to determine whether the remote content
    // differs from our last known local content. This avoids conflicts when timestamps differ but
    // content is identical.
    try {
      if (remoteFile.appProperties && remoteFile.appProperties.lastLocalHash && record.localHash) {
        return String(remoteFile.appProperties.lastLocalHash) !== String(record.localHash);
      }
    } catch (e) {
      // ignore and fall through
    }
    // Prefer any uploader-provided lastLocalMtime stored in appProperties when available as a fallback.
    try {
      if (remoteFile.appProperties && remoteFile.appProperties.lastLocalMtime) {
        const remoteLocalMtime = Number(remoteFile.appProperties.lastLocalMtime) || 0;
        return remoteLocalMtime > (record.localMtime || 0) + 1e3;
      }
    } catch (e) {
      // fallback to modifiedTime comparison
    }
    return remoteMtime > record.driveMtime + 1e3;
  }
  buildConflictPath(filePath, suffix) {
    const dotIndex = filePath.lastIndexOf(".");
    if (dotIndex === -1)
      return `${filePath}.${suffix}`;
    return `${filePath.slice(0, dotIndex)}.${suffix}${filePath.slice(dotIndex)}`;
  }
  async createConflictCopy(remoteFile, remoteData) {
    const conflictPath = this.buildConflictPath(remoteFile.vaultPath, "remote-conflict");
    await this.writeLocalFile(Object.assign({}, remoteFile, { vaultPath: conflictPath }), remoteData);
    return conflictPath;
  }
  async syncRemoteToLocal(remoteFile, remoteMtime) {
    const data = await this.downloadFile(remoteFile);
    const localState = await this.writeLocalFile(remoteFile, data);
    this.syncRecord[remoteFile.vaultPath] = this.buildSyncRecordEntry(remoteFile.vaultPath, {
      driveId: remoteFile.id,
      driveMtime: remoteMtime,
      localMtime: localState.localMtime,
      md5: remoteFile.md5Checksum || "",
      localHash: localState.localHash,
      deleted: false,
      deletedAt: 0,
      dirty: false
    });
  }
  async syncLocalToRemote(localFile, payload, remoteFile) {
    const uploadedFile = await this.uploadFile(localFile, payload, remoteFile == null ? void 0 : remoteFile.id);
    this.syncRecord[localFile.path] = this.buildSyncRecordEntry(localFile.path, {
      driveId: uploadedFile.id,
      driveMtime: new Date(uploadedFile.modifiedTime).getTime(),
      localMtime: localFile.stat.mtime,
      md5: uploadedFile.md5Checksum || "",
      localHash: payload.localHash,
      deleted: false,
      deletedAt: 0,
      dirty: false
    });
  }
  async listDriveFiles(folderId, folderPath = "") {
    const files = [];
    const children = await this.listDriveChildren(folderId);
    for (const child of children) {
      if (child.mimeType === "application/vnd.google-apps.folder") {
        const childPath = (child.appProperties == null ? void 0 : child.appProperties.vaultPath) || (folderPath ? `${folderPath}/${child.name}` : child.name);
        this.folderCache.set(childPath, child.id);
        files.push(...await this.listDriveFiles(child.id, childPath));
      } else {
        const remotePath = (child.appProperties == null ? void 0 : child.appProperties.vaultPath) || (folderPath ? `${folderPath}/${child.name}` : child.name);
        files.push(Object.assign({}, child, { vaultPath: remotePath }));
      }
    }
    return files;
  }
  async downloadFile(remoteFile) {
    const token = await this.getAccessToken();
    const resp = await this.requestWithRetry({
      url: `${DRIVE_API}/files/${remoteFile.id}?alt=media`,
      headers: { Authorization: `Bearer ${token}` }
    });
    return resp.arrayBuffer || new TextEncoder().encode(resp.text || "").buffer;
  }
  async uploadFile(localFile, payload, existingId) {
    const token = await this.getAccessToken();
    const folderId = await this.ensureDriveFolderPath(this.getParentPath(localFile.path));
    const metadata = {
      name: localFile.name,
      appProperties: {
        managedBy: this.manifest.id,
        vaultPath: localFile.path
      }
    };
    // If payload contains a localMtime (timestamp recorded when the file was edited locally),
    // store it on the Drive file so other devices can use it to resolve newer edits.
    try {
      if (payload && payload.localMtime) {
        metadata.appProperties.lastLocalMtime = String(payload.localMtime);
      }
    } catch (e) {
      // ignore
    }
    // Also store a content hash so other devices can detect identical content regardless of clocks.
    try {
      if (payload && payload.localHash) {
        metadata.appProperties.lastLocalHash = String(payload.localHash);
      }
    } catch (e) {
      // ignore
    }
    if (!existingId) {
      metadata.parents = [folderId];
    }
    const multipart = this.buildMultipartBody(metadata, payload.data, payload.mimeType);
    const url = existingId ? `${DRIVE_UPLOAD}/files/${existingId}?uploadType=multipart&fields=id,name,mimeType,modifiedTime,md5Checksum,parents,appProperties,size` : `${DRIVE_UPLOAD}/files?uploadType=multipart&fields=id,name,mimeType,modifiedTime,md5Checksum,parents,appProperties,size`;
    const resp = await this.requestWithRetry({
      url,
      method: existingId ? "PATCH" : "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": `multipart/related; boundary=${multipart.boundary}`
      },
      body: multipart.body
    });
    return resp.json;
  }
  async deleteFile(fileId) {
    const token = await this.getAccessToken();
    await this.requestWithRetry({
      url: `${DRIVE_API}/files/${fileId}`,
      method: "DELETE",
      headers: { Authorization: `Bearer ${token}` }
    });
  }
  // ─── Sync logic ─────────────────────────────────────────────────────────────
  isExcluded(filePath) {
    const patterns = this.settings.excludePatterns.split(",").map((p) => p.trim()).filter(Boolean);
    return patterns.some((p) => filePath.startsWith(p) || filePath.includes(`/${p}`));
  }
  async runSync() {
    if (this.isSyncing) {
      new import_obsidian.Notice("Sync already in progress\u2026");
      return;
    }
    if (!this.settings.refreshToken) {
      new import_obsidian.Notice("GDrive Sync: Please sign in from Settings first.");
      return;
    }
    this.isSyncing = true;
    this.updateStatusBar("syncing");
    this.settings.syncInProgress = true;
    this.settings.lastSyncStartedAt = Date.now();
    await this.persistSettingsData();
    let uploaded = 0, downloaded = 0, deleted = 0, errors = 0;
    try {
      this.folderCache = /* @__PURE__ */ new Map();
      const folderId = await this.ensureVaultFolder();
      this.folderCache.set("", folderId);
      const remoteFiles = await this.listDriveFiles(folderId);
      const remoteMap = {};
      for (const remoteFile of remoteFiles) {
        if (!remoteFile.vaultPath) {
          const migratedRecord = Object.entries(this.syncRecord).find(([filePath, record]) => {
            return this.normalizeSyncRecordEntry(filePath, record).driveId === remoteFile.id;
          });
          if (migratedRecord) {
            remoteFile.vaultPath = migratedRecord[0];
          }
        }
        if (!remoteFile.vaultPath || this.isExcluded(remoteFile.vaultPath))
          continue;
        remoteMap[remoteFile.vaultPath] = remoteFile;
      }
      for (const [filePath, stored] of Object.entries(Object.assign({}, this.syncRecord))) {
        const record = this.normalizeSyncRecordEntry(filePath, stored);
        this.syncRecord[filePath] = record;
        if (!record.deleted)
          continue;
        try {
          if (record.driveId) {
            await this.deleteFile(record.driveId);
            deleted++;
          }
          delete remoteMap[filePath];
          delete this.syncRecord[filePath];
        } catch (e) {
          if ((e == null ? void 0 : e.status) === 404) {
            delete remoteMap[filePath];
            delete this.syncRecord[filePath];
            deleted++;
          } else {
            console.error(`GDrive Sync: failed to delete remote file for ${filePath}`, e);
            errors++;
          }
        }
      }
      const localFiles = this.app.vault.getFiles().filter((f) => !this.isExcluded(f.path));
      for (const localFile of localFiles) {
        try {
          const payload = await this.readLocalFilePayload(localFile);
          const record = this.syncRecord[localFile.path] ? this.normalizeSyncRecordEntry(localFile.path, this.syncRecord[localFile.path]) : null;
          const remote = remoteMap[localFile.path];
          const localMtime = localFile.stat.mtime;
          // If remote exists but is a deletion marker, remove local file and the marker
          if (remote && remote.appProperties && (remote.appProperties.deleted === "1" || remote.appProperties.deleted === "true")) {
            try {
              const existing = this.app.vault.getAbstractFileByPath(localFile.path);
              if (existing instanceof import_obsidian.TFile) {
                await this.app.vault.delete(existing);
                deleted++;
              }
            } catch (e) {
              console.error(`GDrive Sync: failed to delete local file ${localFile.path} for remote deletion marker`, e);
              errors++;
            }
            try {
              if (remote.id)
                await this.deleteFile(remote.id);
            } catch (e) {
              console.error(`GDrive Sync: failed to delete remote deletion marker for ${localFile.path}`, e);
              errors++;
            }
            delete remoteMap[localFile.path];
            continue;
          }

          if (!remote) {
            await this.syncLocalToRemote(localFile, payload);
            uploaded++;
          } else {
            const remoteMtime = new Date(remote.modifiedTime).getTime();
            if (!record) {
              await this.resolveConflict(localFile, payload, remote, remoteMtime);
            } else {
              const localChanged = this.didLocalFileChange(record, payload, localMtime);
              const remoteChanged = this.didRemoteFileChange(record, remote, remoteMtime);
              if (localChanged && !remoteChanged) {
                await this.syncLocalToRemote(localFile, payload, remote);
                uploaded++;
              } else if (remoteChanged && !localChanged) {
                await this.syncRemoteToLocal(remote, remoteMtime);
                downloaded++;
              } else if (localChanged && remoteChanged) {
                // If remote uploader recorded the original local hash and it matches our current
                // payload hash, the contents are identical and we can consider the file synced.
                try {
                  const remoteLastLocalHash = remote && remote.appProperties && remote.appProperties.lastLocalHash;
                  if (remoteLastLocalHash && payload && payload.localHash && String(remoteLastLocalHash) === String(payload.localHash)) {
                    this.syncRecord[localFile.path] = this.buildSyncRecordEntry(localFile.path, Object.assign({}, record, {
                      driveId: remote.id,
                      driveMtime: remoteMtime,
                      localMtime,
                      md5: remote.md5Checksum || record.md5,
                      localHash: payload.localHash,
                      deleted: false,
                      deletedAt: 0,
                      dirty: false
                    }));
                    downloaded++;
                    delete remoteMap[localFile.path];
                    continue;
                  }
                } catch (e) {
                  // fall back to resolving conflict
                }
                await this.resolveConflict(localFile, payload, remote, remoteMtime);
              } else {
                this.syncRecord[localFile.path] = this.buildSyncRecordEntry(localFile.path, Object.assign({}, record, {
                  driveId: remote.id,
                  driveMtime: remoteMtime,
                  localMtime,
                  md5: remote.md5Checksum || record.md5,
                  localHash: payload.localHash,
                  deleted: false,
                  deletedAt: 0,
                  dirty: false
                }));
              }
            }
            delete remoteMap[localFile.path];
          }
        } catch (e) {
          console.error(`GDrive Sync: error processing ${localFile.path}`, e);
          errors++;
        }
      }
      for (const [filePath, remote] of Object.entries(remoteMap)) {
        try {
          if (remote.appProperties && (remote.appProperties.deleted === "1" || remote.appProperties.deleted === "true")) {
            try {
              const existing = this.app.vault.getAbstractFileByPath(filePath);
              if (existing instanceof import_obsidian.TFile) {
                await this.app.vault.delete(existing);
                deleted++;
              }
            } catch (e) {
              console.error(`GDrive Sync: failed to delete local file ${filePath} for remote deletion marker`, e);
              errors++;
            }
            try {
              if (remote.id)
                await this.deleteFile(remote.id);
            } catch (e) {
              console.error(`GDrive Sync: failed to delete remote deletion marker for ${filePath}`, e);
              errors++;
            }
            continue;
          }
          await this.syncRemoteToLocal(remote, new Date(remote.modifiedTime).getTime());
          downloaded++;
        } catch (e) {
          console.error(`GDrive Sync: failed to download ${filePath}`, e);
          errors++;
        }
      }
      this.settings.lastSyncTime = Date.now();
      await this.saveSyncRecord();
      const msg = `GDrive Sync complete \u2014 \u2191${uploaded} \u2193${downloaded} \u2715${deleted}${errors ? ` \u26A0${errors} errors` : ""}`;
      new import_obsidian.Notice(msg, 4e3);
      this.updateStatusBar("idle");
    } catch (e) {
      console.error("GDrive Sync error:", e);
      new import_obsidian.Notice(`GDrive Sync failed: ${e.message}`, 6e3);
      this.updateStatusBar("error", e.message);
    } finally {
      this.settings.syncInProgress = false;
      await this.persistSettingsData();
      this.isSyncing = false;
    }
  }
  async resolveConflict(localFile, payload, remote, remoteMtime) {
    const strategy = this.settings.conflictStrategy;
    const localMtime = localFile.stat.mtime;
    // Prefer lastLocalMtime stored on the remote (uploader-provided) when available
    const remoteEditTimestamp = remote && remote.appProperties && remote.appProperties.lastLocalMtime ? Number(remote.appProperties.lastLocalMtime) : remoteMtime;
    if (strategy === "local" || strategy === "newer" && localMtime >= remoteEditTimestamp) {
      await this.syncLocalToRemote(localFile, payload, remote);
    } else if (strategy === "remote" || strategy === "newer" && remoteEditTimestamp > localMtime) {
      await this.syncRemoteToLocal(remote, remoteMtime);
    } else {
      const remoteData = await this.downloadFile(remote);
      const remoteMimeType = remote.mimeType || this.getMimeTypeForPath(remote.vaultPath);
      if (payload.isText && this.isTextMimeType(remoteMimeType)) {
        const localContent = await this.app.vault.read(localFile);
        const remoteContent = new TextDecoder("utf-8").decode(remoteData);
        const conflictPath = this.buildConflictPath(localFile.path, "conflict");
        await this.ensureLocalFolder(this.getParentPath(conflictPath));
        await this.app.vault.create(
          conflictPath,
          `# CONFLICT \u2014 ${localFile.name}

## Local version

${localContent}

---

## Remote (Google Drive) version

${remoteContent}`
        );
      } else {
        await this.createConflictCopy(remote, remoteData);
      }
      new import_obsidian.Notice(`Conflict detected for ${localFile.path} \u2014 saved both versions.`, 6e3);
    }
  }
  markLocalChange(filePath) {
    const record = this.normalizeSyncRecordEntry(filePath, this.syncRecord[filePath]);
    record.deleted = false;
    record.deletedAt = 0;
    // record the precise edit timestamp when the change was detected
    record.localMtime = Date.now();
    record.dirty = true;
    this.syncRecord[filePath] = record;
  }
  markLocalDelete(filePath) {
    const record = this.normalizeSyncRecordEntry(filePath, this.syncRecord[filePath] || {});
    record.deleted = true;
    record.deletedAt = Date.now();
    record.dirty = false;
    this.syncRecord[filePath] = record;
    // Create a remote deletion marker so other devices see this deletion
    this.createDeletionMarker(filePath).catch((e) => {
      console.error(`GDrive Sync: failed to create deletion marker for ${filePath}`, e);
    });
  }
  async forceUploadAll() {
    this.syncRecord = {};
    await this.saveSyncRecord();
    new import_obsidian.Notice("Sync record cleared \u2014 starting full upload\u2026");
    const previousStrategy = this.settings.conflictStrategy;
    this.settings.conflictStrategy = "local";
    await this.saveSettings();
    try {
      await this.runSync();
    } finally {
      this.settings.conflictStrategy = previousStrategy;
      await this.saveSettings();
    }
  }
  async forceDownloadAll() {
    this.syncRecord = {};
    await this.saveSyncRecord();
    new import_obsidian.Notice("Starting full download from Google Drive\u2026");
    const previousStrategy = this.settings.conflictStrategy;
    this.settings.conflictStrategy = "remote";
    await this.saveSettings();
    try {
      await this.runSync();
    } finally {
      this.settings.conflictStrategy = previousStrategy;
      await this.saveSettings();
    }
  }
  showSyncStatus() {
    const count = Object.entries(this.syncRecord).filter(([filePath, record]) => {
      return !this.normalizeSyncRecordEntry(filePath, record).deleted;
    }).length;
    const last = this.settings.lastSyncTime ? new Date(this.settings.lastSyncTime).toLocaleString() : "Never";
    new SyncStatusModal(this.app, count, last, this.settings.folderName).open();
  }
};
var SyncStatusModal = class extends import_obsidian.Modal {
  constructor(app, count, last, folder) {
    super(app);
    this.count = count;
    this.last = last;
    this.folder = folder;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("gdrive-sync-status-modal");
    contentEl.createEl("h2", { text: "GDrive Sync Status" });
    contentEl.createEl("p", { text: `\u{1F4C1} Drive folder: ${this.folder || "Not set up"}` });
    contentEl.createEl("p", { text: `\u{1F4C4} Tracked files: ${this.count}` });
    contentEl.createEl("p", { text: `\u{1F550} Last sync: ${this.last}` });
    const btn = contentEl.createEl("button", { text: "Close" });
    btn.onclick = () => this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var GDriveSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Google Drive Sync" });
    const infoEl = containerEl.createEl("div");
    infoEl.style.cssText = "background:var(--background-secondary);padding:12px;border-radius:6px;margin-bottom:16px;font-size:0.9em;line-height:1.6";
    infoEl.innerHTML = `
      <b>Setup guide:</b><br>
      1. Go to <a href="https://console.cloud.google.com/" target="_blank">Google Cloud Console</a><br>
      2. Create a project \u2192 Enable <b>Google Drive API</b><br>
      3. Create <b>OAuth 2.0 credentials</b> of type <b>TVs and Limited Input devices</b><br>
      4. Copy Client ID & Secret below, then click <b>Sign in</b><br>
      5. Enter the Google code shown during sign-in. This works on Android too.
    `;
    new import_obsidian.Setting(containerEl).setName("Client ID").setDesc(`OAuth 2.0 Client ID from Google Cloud Console. Active: ${this.plugin.getMaskedClientId()}`).addText(
      (t) => t.setPlaceholder("xxxxx.apps.googleusercontent.com").setValue(this.plugin.settings.clientId).onChange(async (v) => {
        this.plugin.settings.clientId = this.plugin.normalizeOAuthValue(v);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Client Secret").setDesc("OAuth 2.0 Client Secret").addText((t) => {
      t.inputEl.type = "password";
      t.setPlaceholder("GOCSPX-\u2026").setValue(this.plugin.settings.clientSecret).onChange(async (v) => {
        this.plugin.settings.clientSecret = this.plugin.normalizeOAuthValue(v);
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Google Account").setDesc(
      this.plugin.settings.refreshToken ? "\u2705 Signed in" : "Not signed in yet"
    ).addButton(
      (btn) => btn.setButtonText(this.plugin.settings.refreshToken ? "Re-authenticate" : "Sign in with Google").setCta().onClick(() => this.startOAuth())
    ).addButton(
      (btn) => btn.setButtonText("Sign out").onClick(async () => {
        this.plugin.settings.refreshToken = "";
        this.plugin.settings.accessToken = "";
        this.plugin.settings.accessTokenExpiry = 0;
        this.plugin.settings.folderId = "";
        await this.plugin.saveSettings();
        this.display();
      })
    );
    containerEl.createEl("h3", { text: "Sync options" });
    new import_obsidian.Setting(containerEl).setName("Auto-sync interval (minutes)").setDesc("Set to 0 to disable auto-sync").addSlider(
      (s) => s.setLimits(0, 60, 1).setValue(this.plugin.settings.autoSyncInterval).setDynamicTooltip().onChange(async (v) => {
        this.plugin.settings.autoSyncInterval = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync on startup").addToggle(
      (t) => t.setValue(this.plugin.settings.syncOnStartup).onChange(async (v) => {
        this.plugin.settings.syncOnStartup = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Conflict strategy").setDesc("What to do when both local and remote changed since last sync. 'Keep newer' uses local edit timestamps stored on Drive when available.").addDropdown(
      (d) => d.addOption("newer", "Keep newer version").addOption("local", "Always keep local").addOption("remote", "Always keep remote").addOption("ask", "Save both (conflict file)").setValue(this.plugin.settings.conflictStrategy).onChange(async (v) => {
        this.plugin.settings.conflictStrategy = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Exclude patterns").setDesc("Comma-separated paths/prefixes to exclude from sync").addText(
      (t) => t.setValue(this.plugin.settings.excludePatterns).onChange(async (v) => {
        this.plugin.settings.excludePatterns = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Manual actions" });
    new import_obsidian.Setting(containerEl).setName("Sync now").addButton(
      (btn) => btn.setButtonText("\u21BB Sync now").setCta().onClick(() => this.plugin.runSync())
    );
    new import_obsidian.Setting(containerEl).setName("Force upload all").setDesc("Upload every local file to Drive (overwrites remote)").addButton(
      (btn) => btn.setButtonText("Upload all").onClick(() => this.plugin.forceUploadAll())
    );
    new import_obsidian.Setting(containerEl).setName("Force download all").setDesc("Download every file from Drive (overwrites local)").addButton(
      (btn) => btn.setButtonText("Download all").setWarning().onClick(() => this.plugin.forceDownloadAll())
    );
  }
  async startOAuth() {
    this.plugin.normalizeOAuthSettings();
    if (!this.plugin.settings.clientId || !this.plugin.settings.clientSecret) {
      new import_obsidian.Notice("Please enter your Client ID and Secret first.");
      return;
    }
    try {
      const deviceAuth = await this.plugin.requestDeviceCode();
      new OAuthDeviceModal(this.app, this.plugin, deviceAuth, () => this.display()).open();
    } catch (e) {
      new import_obsidian.Notice(`Auth failed: ${e.message}`);
    }
  }
};
var OAuthDeviceModal = class extends import_obsidian.Modal {
  constructor(app, plugin, deviceAuth, onSuccess) {
    super(app);
    this.plugin = plugin;
    this.deviceAuth = deviceAuth;
    this.onSuccess = onSuccess;
    this.cancelled = false;
  }
  async copyText(text) {
    var _a;
    try {
      if ((_a = navigator.clipboard) == null ? void 0 : _a.writeText) {
        await navigator.clipboard.writeText(text);
        return true;
      }
    } catch (e) {
    }
    const textArea = document.createElement("textarea");
    textArea.value = text;
    textArea.setAttribute("readonly", "");
    textArea.style.position = "fixed";
    textArea.style.opacity = "0";
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    const copied = document.execCommand("copy");
    textArea.remove();
    return copied;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("gdrive-sync-auth-modal");
    contentEl.createEl("h3", { text: "Sign in with Google" });
    const codeBox = contentEl.createEl("div");
    codeBox.addClass("gdrive-sync-code-box");
    codeBox.setText(this.deviceAuth.userCode);
    codeBox.title = "Tap to copy code";
    codeBox.onclick = async () => {
      const copied = await this.copyText(this.deviceAuth.userCode);
      new import_obsidian.Notice(copied ? "Code copied to clipboard!" : "Could not copy automatically. Please copy it manually.");
    };
    contentEl.createEl("p", {
      text: "1. Open Google's device sign-in page."
    }).style.cssText = "font-size:0.9em;margin:6px 0";
    contentEl.createEl("p", {
      text: `2. Enter this code exactly: ${this.deviceAuth.userCode}`
    }).style.cssText = "font-size:0.9em;margin:6px 0";
    contentEl.createEl("p", {
      text: "3. Approve access in Google. This window will finish sign-in automatically."
    }).style.cssText = "font-size:0.9em;margin:6px 0;color:var(--text-accent)";
    const urlBox = contentEl.createEl("div");
    urlBox.addClass("gdrive-sync-url-box");
    urlBox.setText(this.deviceAuth.verificationUrl);
    urlBox.title = "Tap to copy URL";
    urlBox.onclick = async () => {
      const copied = await this.copyText(this.deviceAuth.verificationUrl);
      new import_obsidian.Notice(copied ? "URL copied to clipboard!" : "Could not copy automatically. Please copy it manually.");
    };
    const actionsEl = contentEl.createDiv();
    actionsEl.addClass("gdrive-sync-actions");
    const openBtn = actionsEl.createEl("button", { text: "Open Google page" });
    openBtn.onclick = () => window.open(this.deviceAuth.verificationUrl, "_blank");
    const copyBtn = actionsEl.createEl("button", { text: "Copy code" });
    copyBtn.onclick = async () => {
      const copied = await this.copyText(this.deviceAuth.userCode);
      new import_obsidian.Notice(copied ? "Code copied to clipboard!" : "Could not copy automatically. Please copy it manually.");
    };
    const cancelBtn = actionsEl.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    this.statusEl = contentEl.createEl("p", { text: "Waiting for approval in Google..." });
    this.statusEl.addClass("gdrive-sync-auth-status");
    this.waitForApproval();
  }
  async waitForApproval() {
    try {
      await this.plugin.pollForDeviceTokens(
        this.deviceAuth,
        (message) => {
          if (!this.cancelled && this.statusEl) {
            this.statusEl.setText(message);
          }
        },
        () => this.cancelled
      );
      if (this.cancelled)
        return;
      new import_obsidian.Notice("\u2705 Successfully signed in to Google Drive!");
      this.onSuccess();
      this.close();
    } catch (e) {
      if (this.cancelled || e.message === "cancelled")
        return;
      if (this.statusEl) {
        this.statusEl.setText(e.message);
      }
      new import_obsidian.Notice(`Auth failed: ${e.message}`, 6e3);
    }
  }
  onClose() {
    this.cancelled = true;
    this.contentEl.empty();
  }
};
 